MyAspNetCoreApp.Web/Models/Visitor.cs
namespace MyAspNetCoreApp.Web.Models
{
    public class Visitor
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public DateTime Created { get; set; }
    }
}

MyAspNetCoreApp.Web/ViewModels/VisitorViewModel.cs
namespace MyAspNetCoreApp.Web.ViewModels
{
    public class VisitorViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public DateTime Created { get; set; }
    }
}

MyAspNetCoreApp.Web/Controllers/HomeController.cs
using AutoMapper;
using Azure.Core;
using Microsoft.AspNetCore.Mvc;
using MyAspNetCoreApp.Web.Filters;
using MyAspNetCoreApp.Web.Models;
using MyAspNetCoreApp.Web.ViewModels;
using System.Diagnostics;

namespace MyAspNetCoreApp.Web.Controllers
{
    [LogFilter]
    [Route("[controller]/[action]")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly AppDbContext _context;
        private readonly IMapper _mapper;

        public HomeController(ILogger<HomeController> logger, AppDbContext context,IMapper mapper)
        {
            _logger = logger;
            _context = context;
            _mapper = mapper;
        }
        [Route("/")]
        [Route("/Home")]
        [Route("/Home/Index")]
        public IActionResult Index()
        {
            var products = _context.Products.OrderByDescending(x => x.Id).Select(x=>new ProductPartialViewModel()
            {
                Id=x.Id,
                Name=x.Name,
                Price=x.Price,
                Stock=x.Stock
            }).ToList();
            ViewBag.productListPartialViewModel = new ProductListPartialViewModel()
            {
                Products = products
            };
            return View();
        }
        [CustomExceptionFilter]
        public IActionResult Privacy()
        {
            throw new Exception("Veritabani ile ilgili bir hata geldi");
            var products = _context.Products.OrderByDescending(x => x.Id).Select(x => new ProductPartialViewModel()
            {
                Id = x.Id,
                Name = x.Name,
                Price = x.Price,
                Stock = x.Stock
            }).ToList();
            ViewBag.productListPartialViewModel = new ProductListPartialViewModel()
            {
                Products = products
            };
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(ErrorViewModel errorViewModel)
        {
            errorViewModel.RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;

            return View(errorViewModel);
        }
        public IActionResult Visitor()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SaveVisitorComment(VisitorViewModel visitorViewModel)
        {
            try
            {
                var visitor = _mapper.Map<Visitor>(visitorViewModel);
                visitor.Created = DateTime.Now;
                _context.Visitors.Add(visitor);
                _context.SaveChanges();
                TempData["result"] = "Comment saved";
            }
            catch (Exception)
            {
                TempData["result"] = "Error";
            }
            return RedirectToAction(nameof(HomeController.Visitor));
        }
    }
}

MyAspNetCoreApp.Web/Views/Shared/ViewComponents/ProductListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyAspNetCoreApp.Web.Models;
using MyAspNetCoreApp.Web.ViewModels;

namespace MyAspNetCoreApp.Web.Views.Shared.ViewComponents
{
    //[ViewComponent(Name ="p-list")] change component name
    public class ProductListViewComponent:ViewComponent
    {
        private readonly AppDbContext _context;

        public ProductListViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(int type=1)
        {
            var viewmodles = _context.Products.Select(x => new ProductListComponentViewModel()
            {
                Name=x.Name,
                Description=x.Description
            }).ToList();
            if (type==1)
            {
                return View("Default",viewmodles);
            }
            else
            {
                return View("Type2",viewmodles);
            }
            
        }

    }
}

MyAspNetCoreApp.Web/Views/Shared/ViewComponents/VisitorViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MyAspNetCoreApp.Web.Models;
using MyAspNetCoreApp.Web.ViewModels;

namespace MyAspNetCoreApp.Web.Views.Shared.ViewComponents
{
    public class VisitorViewComponent:ViewComponent
    {
        private readonly AppDbContext _context;
        private readonly IMapper _mapper;
        public VisitorViewComponent(AppDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var visitors = _context.Visitors.ToList();
            var visitorViewModels = _mapper.Map<List<VisitorViewModel>>(visitors);
            ViewBag.visitorViewModels = visitorViewModels;
            return View();
        }
    }
}

MyAspNetCoreApp.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    var product = new Product() { Id = 1, Name = "Kalem 1", Price = 100, Stock = 200 };
}
<link rel="stylesheet" href="~/css/example.css" asp-append-version="true" />
@section MyCss
{
    <style type="text/css">
     .h1dunya{
         color:red;
         background-color:blue;
     }
     
    </style>
}


@section Scripts
{
    <script type="text/javascript">
    //alert("Sayfamiza hos geldin.")   
    $(document).ready(myfun=>{
        console.log("Sayfamiza hos geldin.");
    })

    </script>
}



<div class="row">
    <div class="col-md-4">
        <partial name="~/PartialViews/_ProductListPartialView.cshtml" model="@ViewBag.productListPartialViewModel" />
    </div>
    <div class="col-md-4">
        @*first method*@
        @*@await Component.InvokeAsync("ProductList",new {type=1}) *@
        @*second method*@
        <vc:product-list type="1"></vc:product-list>
    </div>
    <div class="col-md-4">
        <italic>Asp.Net Core</italic>
        <product-show product="@product"></product-show>
        
        <img src="images/car.jpg" />

        <thumbnail image-src="images/car.jpg"></thumbnail>

    </div>
</div>






<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>


<h1 class="h1dunya">Merhaba Dunya</h1>

<h2 class="example">Harici css</h2>

<partial name="_MenuPartialView"></partial><!--Kullanilmasi tavsiye edilen-->
@await Html.PartialAsync("_MenuPartialView")
@Html.Partial("_MenuPartialView")<!--Kesinlikle kullanma-->

MyAspNetCoreApp.Web/Views/Home/Visitor.cshtml
@{
    ViewData["Title"] = "Visitor";
}

<div class="row">
    <div class="col-md-9">
        <vc:visitor> </vc:visitor>
    </div>
</div>